secret_root: '{{ inventory_dir | realpath }}'
secret_name: 'secret'
secret: '{{ secret_root + "/" + secret_name }}'

owncloud_domain: "cloud.{{ domain }}"
owncloud_db_username: owncloud
owncloud_db_password: "{{ lookup('password', secret + '/' + 'owncloud_db_password', length=32) }}"
owncloud_db_database: owncloud
owncloud_user_password: "{{ lookup('password', secret + '/' + 'owncloud_user_password', length=32) }}"