---
# Installs and configures the Rspamd spam filtering system.

- name: Ensure repository key for Rspamd is in place
  apt_key: url=http://download.opensuse.org/repositories/home:cebka/Debian_8.0/Release.key state=present
  tags:
    - dependencies

- name: Add Rspamd repository
  apt_repository: repo="deb http://download.opensuse.org/repositories/home:/cebka/Debian_8.0/ /"
  tags:
    - dependencies

- name: Install Rspamd and Rmilter
  apt: pkg={{ item }} state=installed update_cache=yes
  with_items:
    - rspamd
    - rmilter
  tags:
    - dependencies

