---
# Installs and configures the Rspamd spam filtering system.

- name: Ensure repository key for Rspamd is in place
  apt_key: url=https://rspamd.com/apt-stable/gpg.key state=present
  when: ansible_architecture != "armv7l"
  tags:
    - dependencies

- name: Ensure yunohost repository key for Rspamd is in place for ARM
  apt_key: url=http://repo.yunohost.org/debian/yunohost.asc state=present
  when: ansible_architecture == "armv7l"
  tags:
    - dependencies

- name: Add Rspamd repository
  apt_repository: repo="deb https://rspamd.com/apt-stable/ {{ ansible_distribution_release }} main"
  when: ansible_architecture != "armv7l"
  tags:
    - dependencies

- name: Add yunohost Rspamd repository for ARM
  apt_repository: repo="deb http://repo.yunohost.org/debian {{ ansible_distribution_release }} stable"
  when: ansible_architecture == "armv7l"
  tags:
    - dependencies

- name: Install Rspamd and Redis
  apt: pkg={{ item }} state=installed update_cache=yes
  with_items:
    - rspamd
    - redis-server
  tags:
    - dependencies

- name: Start redis
  service: name=redis-server state=started

- name: Start rspamd systemd listener
  service: name=rspamd state=started
