- name: Install radicale dependencies
  apt: pkg={{ item }} state=present
  with_items:
    - apache2-utils
  tags:
    - dependencies

- name: Install radicale
  apt: pkg=radicale update_cache=yes
  tags:
    - dependencies

- name: Configure radicale to start at boot
  lineinfile: dest=/etc/default/radicale
              regexp="^ENABLED"
              line="ENABLED=1"

- name: Add radicale user to ssl-cert group
  user: name=radicale groups=ssl-cert append=yes

- name: Set postgres password
  command: sudo -u {{ db_admin_username }} psql -d {{ db_admin_username }} -c "ALTER USER postgres with  password '{{ db_admin_password }}';"

- name: Create database user for radicale
  postgresql_user: login_host=localhost login_user={{ db_admin_username }} login_password="{{ db_admin_password }}" name={{ radicale_db_username }} password="{{ radicale_db_password }}" state=present

- name: Create database for radicale
  postgresql_db: login_host=localhost login_user={{ db_admin_username }} login_password="{{ db_admin_password }}" name={{ radicale_db_database }} state=present owner={{ radicale_db_username }}

- name: Configure Radicale
  template: src=config.j2 dest=/etc/radicale/config group=root owner=root
  notify: restart radicale

- name: Create radicale accounts
  htpasswd: path=/etc/radicale/users name={{ item.name }} password={{ item.password }} crypt_scheme=ldap_sha1 create=yes state=present
  with_items: radicale_accounts

- name: Set firewall rules for radicale
  ufw: rule=allow port={{ radicale_port }} proto=tcp
