- name: Install radicale dependencies
  apt: pkg={{ item }} state=present
  with_items:
    - apache2-utils
    - libapache2-mod-wsgi
    - python-bcrypt
    - python3-bcrypt
    - python-passlib
    - python3-passlib
    - python3-requests
  tags:
    - dependencies

- name: Install radicale dependencies for Debian (or anything else other than Ubuntu 16.04)
  apt: pkg={{ item }} state=present
  with_items:
    - python-pip
  tags:
    - dependencies
  when: ansible_distribution != "Ubuntu" or ansible_distribution_major_version <= "16"

- name: Install radicale
  pip: name=Radicale
  when: ansible_distribution != "Ubuntu" or ansible_distribution_major_version < "16"

- name: Install radicale
  apt: pkg=radicale state=present
  when: ansible_distribution == "Ubuntu" and ansible_distribution_major_version >= "16"

- name: Create the radicale configuration directory
  file: path=/etc/radicale/
        owner=root
        group=root
        mode=755
        state=directory

- name: Copy radicale default file into place
  copy: src=etc_default_radicale dest=/etc/default/radicale mode=0644

- name: Copy radicale logging file into place
  copy: src=etc_radicale_logging dest=/etc/radicale/logging mode=0644

- name: Copy radicale logrotate file into place
  copy: src=etc_logrotate_radicale dest=/etc/logrotate.d/radicale owner=root group=root mode=0644

- name: Copy radicale config file into place
  template: src=config.j2 dest=/etc/radicale/config mode=0644

- name: Copy radicale init file into place
  copy: src=etc_init.d_radicale dest=/etc/init.d/radicale mode=0755
  when: ansible_distribution != "Ubuntu" or ansible_distribution_major_version < "16"

- name: Create radicale accounts
  htpasswd: path=/etc/radicale/users name={{ item.name }} password={{ item.password }} crypt_scheme=bcrypt create=yes state=present
  with_items: radicale_accounts

- name: Create radicale filesystem directory
  file: path={{ radicale_path}} state=directory

- name: Set radicale filesystem ownership
  action: file owner=www-data group=www-data path=/decrypted/radicale recurse=yes state=directory

- name: Create radicale webserver directory
  file: path=/var/www/radicale state=directory

- name: Set radicale ownership
  action: file owner=root group=www-data path=/var/www/radicale recurse=yes state=directory

- name: Create radicale log directory
  file: owner=root group=adm path=/var/log/radicale mode=0777 state=directory

- name: Copy radicale WSGI file into place
  copy: src=var_www_radicale dest=/var/www/radicale/radicale.wsgi mode=0750

- name: Enable Apache WSGI module
  command: a2enmod wsgi creates=/etc/apache2/mods-enabled/wsgi.load
  notify: restart apache

- name: Configure the Apache HTTP server for radicale
  template: src=etc_apache2_sites-available_radicale.j2 dest=/etc/apache2/sites-available/radicale.conf group=root owner=root

- name: Enable the radicale
  command: a2ensite radicale.conf creates=/etc/apache2/sites-enabled/radicale.conf
  notify: restart apache
