
- name: Install wallabag dependencies
  apt: pkg={{ item }} state=present
  with_items:
    - php5
    - php5-curl
    - php5-mcrypt
    - php5-pgsql
    - php5-tidy
  tags:
    - dependencies

- name: Create database user for wallabag
  postgresql_user: login_host=localhost
                   login_user={{ db_admin_username }}
                   login_password="{{ db_admin_password }}"
                   name={{ wallabag_db_username }}
                   password="{{ wallabag_db_password }}"
                   state=present

- name: Create database for wallabag
  postgresql_db: login_host=localhost
                 login_user={{ db_admin_username }}
                 login_password="{{ db_admin_password }}"
                 name={{ wallabag_db_database }}
                 state=present
                 owner={{ wallabag_db_username }}

- name: Get Composer installer
  get_url: url=https://getcomposer.org/installer
           dest=/tmp/composer-installer

- name: Install Composer
  command: php /tmp/composer-installer
           chdir=/root
           creates=/root/composer.phar

- name: Clone wallabag
  git: repo=https://github.com/wallabag/wallabag.git
       dest=/var/www/wallabag
       version={{ wallabag_version }}
       force=True
       accept_hostkey=yes

- name: Create configuration
  template: src=var_www_wallabag_app_config_parameters.yml.j2
            dest=/var/www/wallabag/app/config/parameters.yml

- name: Initialize composer
  command: php /root/composer.phar install --no-dev -o --prefer-dist
           chdir=/var/www/wallabag
           creates=/var/www/wallabag/vendor/autoload.php
  environment:
    SYMFONY_ENV: prod

- name: Install wallabag
  command: php bin/console wallabag:install --env=prod
           chdir=/var/www/wallabag

- name: Set wallabag ownership
  file: owner=root
        group=www-data
        path=/var/www/wallabag
        recurse=yes
        state=directory

- name: Set wallabag permissions
  file: path=/var/www/wallabag/{{ item }}
        mode=0775
        state=directory
        owner=www-data
        group=www-data
        recurse=true
  with_items:
    - bin
    - app/config
    - vendor
    - data
    - app
    - var


- name: Rename existing Apache wallabag virtualhost
  command: mv /etc/apache2/sites-available/wallabag /etc/apache2/sites-available/wallabag.conf removes=/etc/apache2/sites-available/wallabag

- name: Remove old sites-enabled/wallabag symlink (new one will be created by a2ensite)
  file: path=/etc/apache2/sites-enabled/wallabag state=absent

- name: Configure the Apache HTTP server for wallabag
  template: src=etc_apache2_sites-available_wallabag.j2
            dest=/etc/apache2/sites-available/wallabag.conf
            owner=root
            group=root

- name: Enable the wallabag site
  command: a2ensite wallabag.conf
           creates=/etc/apache2/sites-enabled/wallabag.conf
  notify: restart apache
