- name: Create gitolite group
  group: name=git state=present

- name: Create gitolite user
  user: name=git state=present home=/home/git system=yes group=git

- name: Add www-data to the git group
  user: name=www-data groups=git append=yes


- name: Copy the github public key to known hosts
  lineinfile:
        dest=~/.ssh/known_hosts
        regexp=^github.com
        line="github.com ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEAq2A7hRGmdnm9tUDbO9IDSwBK6TbQa+PXYPCPy6rbTrTtw7PHkccKrpp0yVhp5HdEIcKr6pLlVDBfOLX9QUsyCOV0wzfjIJNlGEYsdlLJizHhbn2mUjvSAHQqZETYP81eFzLQNnPHt4EVVUh7VfDESU84KezmD5QlWpXLmvU31/yMf+Se8xhHTvKSCZIFImWwoG6mbUoWf9nzpIoaSjB+weqqUUmpaaasXVal72J+UX2B+2RPW3RcT0eOzQgqlJL3RKrTJvdsjE3JEAvGq3lGHSZXy28G3skua2SmVi/w4yCE6gbODqnTWlg7+wC604ydGXA8VJiS5ap43JXiUFFAaQ=="
        state=present
        create=yes


- name: Download gitolite release
  git:  repo=git://github.com/sitaramc/gitolite
        dest=/home/git/gitolite
        version=v{{ gitolite_version }}

- name: Give git user file permissions
  file: path=/home/git/gitolite
        state=directory
        recurse=yes
        owner=git
        group=git

- name: Install gitolite
  command: ./gitolite/install -ln /usr/local/bin
           chdir=/home/git
           creates=/usr/local/bin/gitolite

- name: Copy .gitolite.rc file
  copy: src=home_git_.gitolite.rc
        dest=/home/git/.gitolite.rc
        group=git
        owner=git
        mode=0644

- name: Copy SSH public key to server
  copy: src=gitolite.pub
        dest=/home/git/{{ main_user_name }}.pub
        group=git
        owner=git
        mode=0644

- name: Setup gitolite
  command: su - git -c 'gitolite setup -pk {{ main_user_name }}.pub'
           chdir=/home/git
