- name: Install Roundcube prerequisites
  apt: pkg={{ item }} state=latest
  with_items:
  - php5-mysql
  - aspell
  - aspell-en
  - php5-enchant
  - php5-curl
  - php5-mcrypt
  - php5-intl

- name: Download Roundcube 1.1.4
  get_url: url=https://downloads.sourceforge.net/project/roundcubemail/roundcubemail/1.1.4/roundcubemail-1.1.4-complete.tar.gz
    dest=/root/roundcubemail-1.1.4-complete.tar.gz

- name: Decompress Roundcube
  unarchive: src=/root/roundcubemail-1.1.4-complete.tar.gz
    dest=/root
    creates=/root/roundcubemail-1.1.4
    copy=no

- name: Move Roundcube to /opt/roundcube
  command: mv roundcubemail-1.1.4 /opt/roundcube
    chdir=/root
    creates=/opt/roundcube

- name: Create Roundcube database user
  mysql_user: name={{ webmail_db_username }}
    password={{ webmail_db_password }}
    priv=*.*:ALL,GRANT
    state=present

- name: Create Roundcube database
  mysql_db: name={{ webmail_db_database }}
    login_user={{ webmail_db_username }}
    login_password={{ webmail_db_password }}
    state=present

- name: Install Roundcube configuration
  template: src=opt_roundcube_config_config.inc.php.j2 dest=/opt/roundcube/config/config.inc.php

- name: Download composer
  get_url: url=https://getcomposer.org/installer
    dest=/tmp/comp.phar

- name: Install composer
  command: php /tmp/comp.phar --install-dir=/usr/local/bin --filename=composer
    creates=/usr/local/bin/composer

- name: Install plugin configuration
  copy: src=opt_roundcube_composer.json
    dest=/opt/roundcube/composer.json
    owner=www-data group=www-data mode=640 force=yes

- name: Install plugins
  command: composer install --no-interaction
    chdir=/opt/roundcube

- name: Add example rules for sieve plugin
  copy: src=opt_roundcube_example.sieve
    dest=/opt/roundcube/example.sieve
    mode=640

- name: Create sieve plugin configuration from its template
  command: cp -p config.inc.php.dist config.inc.php
    chdir=/opt/roundcube/plugins/sieverules
    creates=/opt/roundcube/plugins/sieverules/config.inc.php

- name: Point to example rules in sieve plugin configuration
  lineinfile:
    dest=/opt/roundcube/plugins/sieverules/config.inc.php
    regexp="sieverules_example_file"
    line="$config['sieverules_example_file'] = '/opt/roundcube/example.sieve';"
    state=present

- name: Fix permissions
  file: dest=/opt/roundcube recurse=yes state=directory
    owner=www-data group=www-data

- name: Configure Apache for Roundcube
  template: src=etc_apache2_sites-available_roundcube.j2
    dest=/etc/apache2/sites-available/roundcube.conf
    group=root owner=root force=yes

- name: Enable Roundcube site
  command: a2ensite roundcube.conf creates=/etc/apache2/sites-enabled/roundcube.conf
  notify: restart apache
