---
# Installs and configures shorewall, which in turn uses iptables for firewall management

- name: Install shorewall
  apt: pkg=shorewall state=present

- name: shorewall config file
  template: src=etc_shorewall_rules.j2 dest=/etc/shorewall/rules mode=0400

- name: copy other shorewall config files
  copy: src=etc_shorewall_{{ item }} dest=/etc/shorewall/{{ item }} mode=0400
  with_items:
  - interfaces
  - params
  - policy
  - zones

- name: Ensure that firewall is running on reboot
  copy: src=etc_default_shorewall dest=/etc/default/shorewall mode=0400
  notify: restart shorewall
